### PR TITLE
Reduce default volume

### LINKED ISSUE #400: Default mic level for laptop's built-in mic is quite a bit higher than it should be
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Clean install
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Maybe gnome-control-center?

**Issue/Bug Description:**
After install, the mic input level is set way up near 80%, which is way higher than it needs to be for most laptops. I usually set mine between 20% and 30% on my oryp6 and darp5.
Screenshot from 2022-04-15 18-55-47

**Steps to reproduce (if you know):**
1. Fresh install
2. Check Settings > Sound > Input volume

**Expected behavior:**
Default input level for built-in mic should be around 20%-30%

**Other Notes:**

### PR DESCRIPTION
**Pull request by 13r0ck**
Closes pop-os/beta#400

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

File: src/config/main.lua.d/40-device-defaults.lua [hunk 1]
```diff
@@ -5,6 +5,7 @@ device_defaults.properties = {
   -- when set to false, default nodes and routes are selected based on
   -- their priorities and any runtime changes do not persist after restart
   ["use-persistent-storage"] = true,
+  ["default-volume"] = 0.03,
```
Comment (jackpot51) [inline src/config/main.lua.d/40-device-defaults.lua:8]: Does this set all devices, both input and output, to 3%?

Comment (13r0ck) [reply src/config/main.lua.d/40-device-defaults.lua:8]: Not 3%, the values are not 0->1, it's about 40%. But yes, there is no option do set just input default volume, I could make a upstream PR to change that, but I figure most people have buttons on their keyboard to change output volume easily.

Comment (jackpot51) [reply src/config/main.lua.d/40-device-defaults.lua:8]: That sounds good to me! Default output volume at 40% should also be reasonable.

Comment (XV-02) [reply src/config/main.lua.d/40-device-defaults.lua:8]: Looks like it drops all default volume values to 30%

Comment (jackpot51) [reply src/config/main.lua.d/40-device-defaults.lua:8]: @XV-02 ready to approve?

Comment (13r0ck) [reply src/config/main.lua.d/40-device-defaults.lua:8]: He is testing it with an install with this baked into the iso, just to be sure that this will work for users who purchase our machines.

Comment (XV-02) [reply src/config/main.lua.d/40-device-defaults.lua:8]: Looks like all volume levels (input and output) default to ~30%.

**Review by XV-02 — APPROVED** [review]
Everything looks good, doesn't override user defined values on update, and the default otherwise works.

**Comment by pikdum** [comment]
This might be what's making my audio really quiet after reboot, even at 100% in the top right.
I've been needing to go into alsamixer to make things audible, and the timing matches up.

Some other people with the same issue:
https://old.reddit.com/r/pop_os/comments/uj4hc8/anyone_else_have_really_low_volume_even_at_max/

**Comment by 13r0ck** [comment]
@pikdum seems doubtful, as this PR as just a config file change, you can reverse this on your system and see if it fixes your issue. The file is located at `/usr/share/wireplumber/main.lua.d/40-device-defaults.lua`

Also, closed/merged PRs are not a place to discuss issues. Please use our Mattermost for community support https://chat.pop-os.org/

### Any more comments on this PR will be ignored and marked as off-topic

**Comment by pikdum** [comment]
>  you can reverse this on your system and see if it fixes your issue.

Yeah, that's what I did to confirm and why I made the comment here. :)
Wasn't looking to discuss or get support, just more of a friendly heads-up that this broke things for some people.

**Comment by jackpot51** [comment]
@pikdum could you see if https://github.com/pop-os/wireplumber/pull/2 fixes the issue, and move discussion there?
